export const GET_CLIENT_STAYS_REQUEST = 'GET_CLIENT_STAYS_REQUEST';
export const GET_CLIENT_STAYS_SUCCESS = 'GET_CLIENT_STAYS_SUCCESS';

export const GET_HOST_STAYS_REQUEST = 'GET_HOST_STAYS_REQUEST';
export const GET_HOST_STAYS_SUCCESS = 'GET_HOST_STAYS_SUCCESS';

export const GET_CASEMANAGER_STAYS_REQUEST = 'GET_CASEMANAGER_STAYS_REQUEST';
export const GET_CASEMANAGER_STAYS_SUCCESS = 'GET_CASEMANAGER_STAYS_SUCCESS';

